### ISSUE TITLE
Update port

### ISSUE THREAD

**Issue by anthonydillon** [canonical/summit.ubuntu.com#10]
This project is using the [port (8020) for usn.ubuntu.com](https://discourse.canonical.com/t/default-ports-for-website-projects/142). Please give it a unique port please.

**Comment by petesfrench** [comment]
@anthonydillon I have made a PR [here](https://github.com/canonical/summit.ubuntu.com/pull/11) updating the port to `8048`. Would you be able to update the discourse post pleas, I don't have permission to edit.

**Comment by anthonydillon** [comment]
You should have access now @petesfrench

**Comment by petesfrench** [comment]
@anthonydillon Hi Ant, I still am unable to edit this document: https://discourse.canonical.com/t/default-ports-for-website-projects/142

**Comment by anthonydillon** [comment]
Sorry I had to confirm via email. Done now.
