### ISSUE TITLE
Sign up for updates... where?

### ISSUE THREAD

**Issue by lucyllewy** [canonical/summit.ubuntu.com#7]
## Summary

Someone has blocked my ability to sign up for updates by hiding the location for this.

## Process

- Read the page at https://summit.ubuntu.com
- Try to sign up for updates

## Current and expected result

Current: I'm unable to read the location 🙄
Expected: I'd like to be able to read the location ☺️

## Screenshot

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/147548/183473765-ef021066-bb3b-4650-8c5b-8d3371e5e240.png">

**Comment by petesfrench** [comment]
This issue is being addressed here https://github.com/canonical/summit.ubuntu.com/pull/8
